### ISSUE TITLE
User reports from /r/3Dprinting (all caps submission form title)

### ISSUE THREAD

**Issue by traverseda** [creesch/redditBasic-css-theme-for-reddit#2]
Please disable the all-caps titles when submitting new posts

In case you're not aware of the issue, here's how to reproduce the problem:
Create a new post (text or link)
- Type into the "Title" field
- Notice that everything is caps even if you're not hitting the Shift key Caps Lock is disabled
- Get really confused and hope your post doesn't have an all-caps title when you submit it
- Possibly comment about this in your post text and maybe apologize because you think you're doing something wrong and can't fix it
- Feel really bad if you're one of the unlucky people that did it backwards and the first letter is lower case and everything else is in caps
- This issue is definitely contributing to noise and confusion by a non-trivial number of posters. Anything you can do to investigate would be greatly appreciated by everyone here.

Thanks!

/u/bmemike

---

When I am attempting to place anything within the title area it is in all CAPS. I know it is not a hardware issue, just wondering if you have ran into it on your side?

/u/jhug

---

https://www.reddit.com/r/3Dprinting/submit?selftext=true

Hello, I noticed today that in the self text submission form, the "title" text area unintentionally inherits the CSS directive text-transform: uppercase;. This causes any text which is typed in to display as uppercase. I am running on OS X 10.10 and Google Chrome Version 51.0.2704.103 (64-bit).

Thanks!

/u/KANahas

**Comment by creesch** [comment]
That's probably some reddit regression. My best guess is that they moved some elements around which resulted in the input field now getting that stuff inherited from somewhere else. 

Should be easy enough to fix for someone with a bit of css knowledge and a bit of time if you guys want to give it a shot yourself. The bit of time part is important because I barely have any at the moment. 

Quick and dirty:
- with chrome right click on the input field and select "inspect element" 
- find in the styles tab where it says something with 'text-transform: uppercase;`
- find that part in your css and adjust it. 

Alternatively, wait a bit for me to fix it ;)

**Comment by traverseda** [comment]
I might do a PR in a bit. But time is the issue, yes.

**Comment by creesch** [comment]
I just had a look and I can't reproduce your issue and it seems you have removed the css?

**Comment by traverseda** [comment]
Yeah, we had a fare number of user reports. I made the decision to pull it
for now.

There was also an issue with RES and night mode, which you provided a
snippet to fix. I don't think said snippet ever made it into the master
branch though.

There's a copy of our entire css, including that snippet, here.
http://pastebin.com/pGX8YmBC

We do have a small amount of custom css, and if you can't reproduce it
there's a very real possibility it's coming from that custom css, which I
didn't write. I won't be offended if you close it as "can not reproduce",
and I'll get back to you once I figure out the exact browser/whatever to
reproduce.

On Tue, Jul 5, 2016 at 1:55 PM, creesch notifications@github.com wrote:

> I just had a look and I can't reproduce your issue and it seems you have
> removed the css?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/creesch/redditBasic-css-theme-for-reddit/issues/2#issuecomment-230536844,
> or mute the thread
> https://github.com/notifications/unsubscribe/ACBwBFC__xmtO1gDVF4bRcX_epFKl-BPks5qSoyCgaJpZM4JD9eN
> .

## 

With dread but cautious optimism, Alex Davies.
traverse.da@gmail.com
+1 902 580 1543

**Comment by nathanielhudson** [comment]
Hey there! /u/nathanielhudson from /r/3Dprinting here. I'm not sure exactly what happened. The /r/3Dprinting CSS is not stock redditBasic, and it looks like at some point over a year ago some css was added to all-caps titles which was a little over-broadly applied. I guess nobody noticed until now? Or the admins changed how the page HTML is rendered? In either case, it was just a case of .submit-page .title also applying to the title input field.

I've fixed it on our end. Thanks!

**Comment by traverseda** [comment]
Thanks a bunch. Sorry for bothering you with this creesch.

On Wed, Jul 6, 2016 at 12:35 AM, Nathaniel Hudson notifications@github.com
wrote:

> Hey there! /u/nathanielhudson from /r/3Dprinting here. I'm not sure
> exactly what happened. The /r/3Dprinting CSS is not stock redditBasic, and
> it looks like at some point over a year ago some css was added to all-caps
> titles which was a little over-broadly applied. I guess nobody noticed
> until now? Or the admins changed how the page HTML is rendered. In either
> case, it was just a case of .submit-page .title also applying to the title
> input field.
> 
> I've fixed it on our end though.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/creesch/redditBasic-css-theme-for-reddit/issues/2#issuecomment-230663364,
> or mute the thread
> https://github.com/notifications/unsubscribe/ACBwBK5-wPN4LAEqGVXnCvUsrfUxvg9yks5qSyJzgaJpZM4JD9eN
> .

## 

With dread but cautious optimism, Alex Davies.
traverse.da@gmail.com
+1 902 580 1543
